/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'quantity' : bigint, 'packageId' : bigint }
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'contactInfo' : string,
  'cartItems' : Array<CartItem>,
  'totalAmount' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export type Platform = { 'tiktok' : null } |
  { 'instagram' : null } |
  { 'facebook' : null } |
  { 'youtube' : null };
export interface ServicePackage {
  'id' : bigint,
  'deliveryEstimate' : string,
  'serviceType' : ServiceType,
  'description' : string,
  'platform' : Platform,
  'available' : boolean,
  'priceDh' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export type ServiceType = { 'views' : null } |
  { 'likes' : null } |
  { 'followers' : null };
export interface _SERVICE {
  'addServicePackage' : ActorMethod<
    [Platform, ServiceType, bigint, bigint, bigint, string, string],
    bigint
  >,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAvailableServices' : ActorMethod<[], Array<ServicePackage>>,
  'placeOrder' : ActorMethod<[string, string, Array<CartItem>], bigint>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateServicePackage' : ActorMethod<
    [bigint, bigint, bigint, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];