/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Platform = IDL.Variant({
  'tiktok' : IDL.Null,
  'instagram' : IDL.Null,
  'facebook' : IDL.Null,
  'youtube' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'views' : IDL.Null,
  'likes' : IDL.Null,
  'followers' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat,
  'packageId' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'contactInfo' : IDL.Text,
  'cartItems' : IDL.Vec(CartItem),
  'totalAmount' : IDL.Nat,
});
export const ServicePackage = IDL.Record({
  'id' : IDL.Nat,
  'deliveryEstimate' : IDL.Text,
  'serviceType' : ServiceType,
  'description' : IDL.Text,
  'platform' : Platform,
  'available' : IDL.Bool,
  'priceDh' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addServicePackage' : IDL.Func(
      [Platform, ServiceType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAvailableServices' : IDL.Func([], [IDL.Vec(ServicePackage)], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(CartItem)],
      [IDL.Nat],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateServicePackage' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Platform = IDL.Variant({
    'tiktok' : IDL.Null,
    'instagram' : IDL.Null,
    'facebook' : IDL.Null,
    'youtube' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'views' : IDL.Null,
    'likes' : IDL.Null,
    'followers' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const CartItem = IDL.Record({ 'quantity' : IDL.Nat, 'packageId' : IDL.Nat });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'contactInfo' : IDL.Text,
    'cartItems' : IDL.Vec(CartItem),
    'totalAmount' : IDL.Nat,
  });
  const ServicePackage = IDL.Record({
    'id' : IDL.Nat,
    'deliveryEstimate' : IDL.Text,
    'serviceType' : ServiceType,
    'description' : IDL.Text,
    'platform' : Platform,
    'available' : IDL.Bool,
    'priceDh' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addServicePackage' : IDL.Func(
        [Platform, ServiceType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAvailableServices' : IDL.Func([], [IDL.Vec(ServicePackage)], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(CartItem)],
        [IDL.Nat],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateServicePackage' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };