/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'quantity' : bigint, 'serviceId' : bigint }
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'contactInfo' : string,
  'cartItems' : Array<CartItem>,
  'totalAmount' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export type Platform = { 'tiktok' : null } |
  { 'instagram' : null } |
  { 'facebook' : null } |
  { 'youtube' : null };
export interface Service {
  'id' : bigint,
  'deliveryEstimate' : string,
  'serviceType' : ServiceType,
  'baseUnitPriceDh' : bigint,
  'description' : string,
  'platform' : Platform,
  'available' : boolean,
  'baseUnitPriceCents' : bigint,
}
export type ServiceType = { 'views' : null } |
  { 'likes' : null } |
  { 'followers' : null };
export interface Testimonial {
  'customerName' : string,
  'serviceType' : ServiceType,
  'testimonialText' : string,
  'rating' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addService' : ActorMethod<
    [Platform, ServiceType, bigint, bigint, string, string],
    bigint
  >,
  'addTestimonial' : ActorMethod<
    [string, ServiceType, string, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getAvailableServices' : ActorMethod<[], Array<Service>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, string, Array<CartItem>], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateService' : ActorMethod<[bigint, bigint, bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];